### ISSUE TITLE
Certain sim wont rip!

### ISSUE THREAD

**Issue by Dmariiee** [CmarNYC-Tools/TS4SimRipper#14]
I have tried over and over again andthis certain sim will not rip, all other sims rip just fine. Here is the log from it if this would help. Please help!
[SimBuilderLog.txt](https://github.com/user-attachments/files/16983275/SimBuilderLog.txt)

**Comment by andrews4s** [comment]
Hi @Dmariiee, can you attach the file generated from the "Save Sim Troubleshooting Info" button?

**Comment by Dmariiee** [comment]
> Hi @Dmariiee, can you attach the file generated from the "Save Sim Troubleshooting Info" button?

[KiraLehman_TroubleShoot.zip](https://github.com/user-attachments/files/16987339/KiraLehman_TroubleShoot.zip)
i saw something about te body preset but i took it off of her and the same thing happens.

**Comment by andrews4s** [comment]
I've uploaded a new version of the program that should fix the issue. Please try that and let me know if it works for you.

https://github.com/CmarNYC-Tools/TS4SimRipper/releases/tag/3.14.2.5

**Comment by Dmariiee** [comment]
it worked! thank you!!!
