### ISSUE TITLE
Ts4ripper face error

### ISSUE THREAD

**Issue by raeeee96** [CmarNYC-Tools/TS4SimRipper#2]
Hi! I tried to post this under the thread on S4S, but I wasn't able to. I've been having this issue with the recent update of Ripper I'm not sure if it has to do with the newest game update, but I tried to uninstall the game and reinstall and that did not work. Any help would be greatly appreciated. I have added the troubleshooting info as well as a screenshot of the issue.
[sim_TroubleShoot.zip](https://github.com/CmarNYC-Tools/TS4SimRipper/files/15143539/sim_TroubleShoot.zip)
![Screenshot (7)](https://github.com/CmarNYC-Tools/TS4SimRipper/assets/168372837/708a0ae1-3778-4199-be2f-9d1338d06e05)

**Comment by nvcn4sims** [comment]
I am also having the same error with quite a few of my sims! I'll provide some of my trouble shooting info too and maybe that would help the devs? Mine seem to be too big of files so I hope drive links are okay.
https://drive.google.com/file/d/1uoiXV0fCTHZ3Vk6bN-9QTU-6wtK7W1ny/view?usp=sharing

**Comment by andrews4s** [comment]
Hi @raeeee96,
I tried loading your files and the problem with the eye isn't happening for me. Do you have any default replacements that could affect the face? If so, maybe I need them in order to see the problem.
<img width="890" alt="faceError_raeeee96" src="https://github.com/CmarNYC-Tools/TS4SimRipper/assets/15205112/ad6afd25-c8c7-4191-9a68-54c5cf3f5201">

**Comment by raeeee96** [comment]
Hi @andrews4s 
In my game currently the only default eyes I have are the Pralinesims Irene default eyes from the genetics remix set. I hope this helps !

**Comment by andrews4s** [comment]
@raeeee96 
I tried adding the eyes to my mods folder and still can't replicate the issue in your screenshot. Can you try setting the mods folder in sim ripper to a new folder that only has the package files from the sim_Troubleshoot.zip in it and see if you still have the problem with that sim?

@nvcn4sims 
I'm also not seeing any issue when opening the files that you sent. Can you post a screenshot of the issue? This is what I see.
<img width="482" alt="nvcn4sims_sim" src="https://github.com/CmarNYC-Tools/TS4SimRipper/assets/15205112/040b2c31-286c-48a2-bff3-1f7e90287790">

**Comment by nvcn4sims** [comment]
Huh, that is really strange. I'm confused on what it could be but this is what he looks like in mine:
![error](https://github.com/CmarNYC-Tools/TS4SimRipper/assets/170211020/f15bf504-c7e5-4035-8fd0-e302bb908c2a)

**Comment by raeeee96** [comment]
Hi @andrews4s 
I also tried trying the mod folder, but I also got the same error.

**Comment by andrews4s** [comment]
Hi @raeeee96 and @nvcn4sims,
I think I found the problem. It is loading the unpatched version of the sim head mesh. Can you try this updated version and see if it fixes things?
[Uploading CmarNYC_TS4SimRipper_3_14_2_4.zip…]()

**Comment by nvcn4sims** [comment]
> Hi @raeeee96 and @nvcn4sims, I think I found the problem. It is loading the unpatched version of the sim head mesh. Can you try this updated version and see if it fixes things? [CmarNYC_TS4SimRipper_3_14_2_4.zip](https://github.com/user-attachments/files/15539608/CmarNYC_TS4SimRipper_3_14_2_4.zip)

YES! IT'S FIXED! Another error I was having where a sim's nose was deformed has also been fixed with this version! Thank you so much <3
![Uploading fixed nico.png…]()

**Comment by andrews4s** [comment]
@nvcn4sims I'm glad it worked. I've uploaded that version to the releases. I'll close the issue out once @raeeee96 can confirm it fixed their sim as well.

**Comment by raeeee96** [comment]
Hey @andrews4s It works now. Thank You so much!

**Comment by andrews4s** [comment]
You're welcome! Thanks for confirming the fix.
