### ISSUE TITLE
TSR Face Issue with NEW UPDATE 

### ISSUE THREAD

**Issue by MoonSims** [CmarNYC-Tools/TS4SimRipper#4]
Hi I'm wondering and hoping sim ripper gets updated soon to the new sims 4 recent update ! ever since I updated my game I had a big issue with my OBJ messing up this wasn't happening until I updated my game so I'm wondering if their is a way to fix it. I've been waiting 2 weeks hoping for a new update on sim ripper 
![TSRSRSRSRS](https://github.com/CmarNYC-Tools/TS4SimRipper/assets/168618447/1fbd6665-dcab-4df6-bb65-d96503cf53d3)
this is what it looks like is there any way to fix it or is the update coming soon ??

**Comment by rouletvilla** [comment]
seconding this, i am also having issues 
![2024-05-20 21_08_14-@Viko - Discord](https://github.com/CmarNYC-Tools/TS4SimRipper/assets/170383099/da8cad0b-b425-4f2d-81f2-cc2f6033e13d)

have tried removing bad mods / presets / sliders but to no avail, and happens to untouched maxis sims

**Comment by andrews4s** [comment]
Hi @MoonSims,
Can you attach the troubleshooting info zip for the sims in your screenshots?

**Comment by Ispitoutmymonster** [comment]
Im also having the same issue with no luck

**Comment by PisceSims** [comment]
I am having this same issue as well

**Comment by andrews4s** [comment]
Can someone with this issue try again with the new version 3.14.2.4? It fixed another similar issue.

https://github.com/CmarNYC-Tools/TS4SimRipper/releases/tag/3.14.2.4

**Comment by Ispitoutmymonster** [comment]
I tried the new version and it fixed for me, Thank you so much!

**Comment by andrews4s** [comment]
@Ispitoutmymonster, thanks for confirming!
