### ISSUE TITLE
Error Setting up Frame Modifer

### ISSUE THREAD

**Issue by SimpleSimmer** [CmarNYC-Tools/TS4SimRipper#5]
Hi I keep getting this error code, can anyone explain how I can fix this please

![Screenshot 2024-05-07 111450](https://github.com/CmarNYC-Tools/TS4SimRipper/assets/169175764/121ba35a-6541-4cb3-845b-2473c879d5dd)

**Comment by SimpleSimmer** [comment]
![image](https://github.com/CmarNYC-Tools/TS4SimRipper/assets/169175764/dd1c2dc1-1003-43d1-86da-8305ecd58a05)

**Comment by iza-bittencourt** [comment]
The same is happening to me, how did you solve it?

**Comment by iza-bittencourt** [comment]
The same is happening to me, how did you solve it?
